#=

Q.

This problem concerns the notation for simultaneous assignment, for example $( X Y ) \leftarrow ( Z W )$.

a. We abbreviated the special case $( X Y ) \leftarrow ( Y X )$ by $X \leftrightarrow Y$.
Write code for this swap using only simple assignment statements and a temporary variable $T$.

b. Generalizing part (a), suppose we want to rotate the values of $n$ variables $X_1, ..., X_n$ as follows:
\begin{pmatrix}
 X_1 \\
 X_2 \\
 \vdots \\
 X_{n-1} \\
 X_n
\end{pmatrix} \leftarrow
\begin{pmatrix}
 X_2 \\
 X_3 \\
 \vdots \\
 X_n \\
 X_1
\end{pmatrix}
Write code for this operation using only simple assignments and as few temporary variables as possible.

c. Suppose we need to translate the notation
\begin{pmatrix}
 X_1 \\
 \vdots \\
 X_n
\end{pmatrix} \leftarrow
\begin{pmatrix}
 a_1 \\
 \vdots \\
 a_n
\end{pmatrix}
into some programming language that does not provide these simultaneous
assignments. Translate the general simultaneous assignment
into code that uses only simple assignments, again using as few
temporary variables as possible. (The $a_i$ are arbitrary expressions.)

d. Now suppose that we are working in a language where
simultaneous assignments are not available, but there is a primitive swap
operation $X \leftrightarrow Y$ that exchanges the values of $X$ and $Y$. Solve
parts (b) and (c) again.

A.

a.

#+BEGIN_SRC julia :kernel julia
  # Since julia can'tpass Int by reference, I didn't use function.
  X = 1
  Y = 2

  T = X
  X = Y
  Y = T
  print(X)
  print(Y)
#+END_SRC

b.

#+BEGIN_SRC julia :kernel julia
  function RotateOne(T::Array{Int})
      tmp = T[1]
      for i in 1:length(T)-1
          T[i] = T[i+1]
      end
      T[end] = tmp
  end
#+END_SRC

#+BEGIN_SRC julia :kernel julia
  T = [1 2 3 4 5]
  RotateOne(T)
  print(T)
#+END_SRC

c.

#+BEGIN_SRC julia :kernel julia
  function SimultaneousAssignments(X::Array{Int}, Y::Array{Int})
      for i in 1:length(X)
          X[i] = Y[i]
      end
  end
#+END_SRC

#+BEGIN_SRC julia :kernel julia
  X = [1 2 3 4 5]
  Y = [6 7 8 9 0]
  SimultaneousAssignments(X, Y)
  print(X)
#+END_SRC

d.

#+BEGIN_SRC julia :kernel julia
  function RotateOne(T::Array{Int})
      for i in 1:length(T)-1
          T[i], T[i+1] = T[i+1], T[i]
      end
  end

  function SimultaneousAssignments(X::Array{Int}, Y::Array{Int})
      for i in 1:length(X)
          X[i], Y[i] = Y[i], X[i]
      end
  end
#+END_SRC

#+BEGIN_SRC julia :kernel julia
  T = [1 2 3 4 5]
  RotateOne(T)
  print(T)

  X = [1 2 3 4 5]
  Y = [6 7 8 9 0]
  SimultaneousAssignments(X, Y)
  print(X)
#+END_SRC

=#
