#lang sicp
(define (make-interval a b) (cons a b))
(define (lower-bound interval) (min (car interval) (cdr interval)))
(define (upper-bound interval) (max (car interval) (cdr interval)))

(define (mul-interval x y)    
  (let ((up-x (upper-bound x))
        (up-y (upper-bound y))
        (low-x (lower-bound x))
        (low-y (lower-bound y)))
    (cond ((and (>= low-x 0) (>= low-y 0))
           (make-interval (* up-x up-y) (* low-x low-y)))
          ((and (>= low-x 0) (<= up-y 0))
           (make-interval (* low-x up-y) (* up-x low-y)))
          ((and (>= low-x 0) (<= (* low-y up-y) 0))
           (make-interval (* up-x up-y) (* up-x low-y)))
          ((and (<= up-x 0) (>= low-y 0))
           (make-interval (* up-x low-y) (* low-x up-y)))
          ((and (<= up-x 0) (<= up-y 0))
           (make-interval (* low-x low-y) (* up-x up-y)))
          ((and (<= up-x 0) (<= (* low-y up-y) 0))
           (make-interval (* low-x low-y) (* low-x up-y)))
          ((and (<= (* low-x up-x) 0) (>= low-y 0))
           (make-interval (* up-x up-y) (* low-x up-y)))
          ((and (<= (* low-x up-x) 0) (<= up-y 0))
           (make-interval (* low-x low-y) (* up-x low-y)))
          ((and (<= (* low-x up-x) 0) (<= (* low-y up-y) 0))
           (make-interval (max (* up-x up-y) (* low-x low-y)) (min (* up-x low-y) (* low-x up-y)))))))

(mul-interval (make-interval 1 2) (make-interval 3 4))
(mul-interval (make-interval 1 2) (make-interval -3 4))
(mul-interval (make-interval 1 2) (make-interval 3 -4))
(mul-interval (make-interval 1 2) (make-interval -3 -4))
(mul-interval (make-interval -1 2) (make-interval 3 4))
(mul-interval (make-interval -1 2) (make-interval -3 4))
(mul-interval (make-interval -1 2) (make-interval 3 -4))
(mul-interval (make-interval -1 2) (make-interval -3 -4))
(mul-interval (make-interval 1 -2) (make-interval 3 4))
(mul-interval (make-interval 1 -2) (make-interval -3 4))
(mul-interval (make-interval 1 -2) (make-interval 3 -4))
(mul-interval (make-interval 1 -2) (make-interval -3 -4))
(mul-interval (make-interval -1 -2) (make-interval 3 4))
(mul-interval (make-interval -1 -2) (make-interval -3 4))
(mul-interval (make-interval -1 -2) (make-interval 3 -4))
(mul-interval (make-interval -1 -2) (make-interval -3 -4))
(mul-interval (make-interval -1 2) (make-interval -3 0))
(mul-interval (make-interval -1 2) (make-interval 0 0))