#lang sicp
(define (make-segment start end) (cons start end))
(define (start-segment seg) (car seg))
(define (end-segment seg) (cdr seg))

(define (make-point x y) (cons x y))
(define (x-point pair) (car pair))
(define (y-point pair) (cdr pair))
(define (midpoint-segment seg)
  (define (average a b) (/ (+ a b) 2))
  (make-point (average (x-point (start-segment seg)) (x-point (end-segment seg)))
              (average (y-point (start-segment seg)) (y-point (end-segment seg)))))
(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")")
  (newline))

(define line-segment (make-segment (make-point 1 1) (make-point 5 5)))
(print-point (midpoint-segment line-segment))